-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["satellite"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 20, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   42, 9  ,  -42, 9  ,  -42, -9  ,  42, -9  }
                    }
                    
                    
                    
		}
		
		, 
		["star"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   0, 11.5  ,  -8, 5  ,  -5, -5  ,  6, -5  ,  9, 5  ,  13, 21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   9, 5  ,  6, -5  ,  21, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   6, -5  ,  -5, -5  ,  0, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -5, -5  ,  -8, 5  ,  -21, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -8, 5  ,  0, 11.5  ,  -13, 21  }
                    }
                    
                    
                    
		}
		
		, 
		["cannon"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 4, groupIndex = 0 },
                    shape = {   5.5, 16.5  ,  -5.5, 16.5  ,  -8.5, 14.5  ,  -8.5, 9.5  ,  6.5, 7.5  ,  8.5, 9.5  ,  8.5, 14.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 4, groupIndex = 0 },
                    shape = {   8.5, -13.5  ,  8.5, 1.5  ,  6.5, 2.5  ,  -6.5, 2.5  ,  -8.5, 1.5  ,  -8.5, -13.5  ,  -5.5, -16.5  ,  5.5, -16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 4, groupIndex = 0 },
                    shape = {   -8.5, 9.5  ,  -6.5, 7.5  ,  6.5, 2.5  ,  6.5, 7.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 2, maskBits = 4, groupIndex = 0 },
                    shape = {   -6.5, 2.5  ,  6.5, 2.5  ,  -6.5, 7.5  }
                    }
                    
                    
                    
		}
		
		, 
		["rocket"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 30, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -14.5, 14  ,  13.5, 13  ,  31, 41  ,  13.5, 46.5  ,  -13.5, 47  ,  -31.5, 42.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 30, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -13.5, 47  ,  13.5, 46.5  ,  6.5, 62  ,  -6.5, 62  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 30, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -14.5, -34  ,  -8.5, -51  ,  -3.5, -60  ,  3.5, -60  ,  8.5, -51  ,  13.5, -34  ,  13.5, 13  ,  -14.5, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 30, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   3.5, -60  ,  -3.5, -60  ,  -0.5, -62  }
                    }
                    
                    
                    
		}
		
		, 
		["ship"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 15, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   9.5, -12.5  ,  8.5, 7  ,  -9.5, -13  ,  0.5, -27  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 15, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -9.5, -37.5  ,  -6.5, -31  ,  -9.5, -13  ,  -20.5, 4  ,  -23.5, -20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 15, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   8.5, 7  ,  9.5, -12.5  ,  23.5, -20  ,  20.5, 4  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 15, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   23.5, -20  ,  9.5, -12.5  ,  7.5, -31  ,  10.5, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 15, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   8.5, 34  ,  4.5, 37  ,  -4.5, 37  ,  -8.5, 7  ,  -9.5, -13  ,  8.5, 7  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 15, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -9.5, -13  ,  -8.5, 7  ,  -20.5, 4  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 15, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -8.5, 7  ,  -4.5, 37  ,  -8.5, 34  }
                    }
                    
                    
                    
		}
		
		, 
		["ufo"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.6, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -10, -3  ,  10, -3  ,  17, 20  ,  10, 24  ,  -10, 24  ,  -19, 18  ,  -25, 11  ,  -25, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.6, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   25, 10  ,  17, 20  ,  10, -3  ,  25, 0  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.6, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -10, -18  ,  -7, -22  ,  -4, -24  ,  4, -24  ,  7, -22  ,  10, -17  ,  10, -3  ,  -10, -3  }
                    }
                    
                    
                    
		}
		
		, 
		["leaf"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   17.5, -6.5  ,  14, 7.5  ,  10, 14.5  ,  -18, -0.5  ,  -14, -7.5  ,  -5, -13.5  ,  9, -17.5  ,  18, -18.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -14, 13.5  ,  -18, 6.5  ,  -18, -0.5  ,  10, 14.5  ,  4, 18  ,  -6, 18.5  }
                    }
                    
                    
                    
		}
		
		, 
		["meteor"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 20, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   14.5, -17  ,  21.5, -5  ,  20.5, 9  ,  13.5, 21  ,  0.5, 23  ,  -20.5, 8  ,  -11.5, -17  ,  1.5, -23  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 20, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -11.5, -17  ,  -20.5, 8  ,  -21.5, -7  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 20, friction = 0, bounce = 0.1, 
                    filter = { categoryBits = 8, maskBits = 13, groupIndex = 0 },
                    shape = {   -20.5, 8  ,  0.5, 23  ,  -13.5, 19  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

